# Generated by Django 4.2 on 2023-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptomodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='giftcardmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
