# Generated by Django 4.2 on 2023-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeBase', '0002_alter_cryptomodel_logo_alter_giftcardmodel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_status', models.BooleanField(default=False)),
                ('testimony', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cryptomodel',
            name='first_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftcardmodel',
            name='first_page',
            field=models.BooleanField(default=False),
        ),
    ]
